# Generated by Django 3.0.6 on 2020-06-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Featured',
            field=models.BooleanField(default=False),
        ),
    ]
